<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class LecturerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $password = Hash::make('password');

        DB::table('lecturer')->insertOrIgnore([
            [
                'staffNum' => 'L1001',
                'fName' => 'Christopher',
                'lName' => 'Bahng',
                'ic' => '971003015001',
                'email' => 'christopher.bahng@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '12',
                'subNum' => '1234567',
                'department' => 'Data Engineering',
                'officeBuilding' => 'N28',
                'officeFloor' => '3',
                'officeRoom' => '301',
                'qualification' => 'PhD in Data Engineering',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1002',
                'fName' => 'Minho',
                'lName' => 'Lee',
                'ic' => '981025015002',
                'email' => 'minho.lee@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '13',
                'subNum' => '2234567',
                'department' => 'Data Engineering',
                'officeBuilding' => 'N28A',
                'officeFloor' => '2',
                'officeRoom' => '205',
                'qualification' => 'PhD in Data Science',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1003',
                'fName' => 'Changbin',
                'lName' => 'Seo',
                'ic' => '990811015003',
                'email' => 'changbin.seo@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '19',
                'subNum' => '3334567',
                'department' => 'Networks & Security',
                'officeBuilding' => 'N28',
                'officeFloor' => '4',
                'officeRoom' => '410',
                'qualification' => 'PhD in Network Security',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1004',
                'fName' => 'Hyunjin',
                'lName' => 'Hwang',
                'ic' => '000320015004',
                'email' => 'hyunjin.hwang@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '17',
                'subNum' => '4444567',
                'department' => 'Artificial Intelligence',
                'officeBuilding' => 'N28A',
                'officeFloor' => '1',
                'officeRoom' => '112',
                'qualification' => 'PhD in Artificial Intelligence',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1005',
                'fName' => 'Jisung',
                'lName' => 'Han',
                'ic' => '000914015005',
                'email' => 'jisung.han@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '14',
                'subNum' => '5554567',
                'department' => 'Bioinformatics',
                'officeBuilding' => 'N28',
                'officeFloor' => '2',
                'officeRoom' => '220',
                'qualification' => 'PhD in Computational Biology',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1006',
                'fName' => 'Felix',
                'lName' => 'Lee',
                'ic' => '000915015006',
                'email' => 'felix.lee@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '16',
                'subNum' => '6664567',
                'department' => 'Software Engineering',
                'officeBuilding' => 'N28',
                'officeFloor' => '3',
                'officeRoom' => '315',
                'qualification' => 'Master of Computer Science',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1007',
                'fName' => 'Seungmin',
                'lName' => 'Kim',
                'ic' => '000922015007',
                'email' => 'seungmin.kim@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '18',
                'subNum' => '7774567',
                'department' => 'Data Engineering',
                'officeBuilding' => 'N28A',
                'officeFloor' => '2',
                'officeRoom' => '208',
                'qualification' => 'PhD in Big Data Analytics',
                'facCode' => 'FC',
            ],
            [
                'staffNum' => 'L1008',
                'fName' => 'Jeongin',
                'lName' => 'Yang',
                'ic' => '010208015008',
                'email' => 'jeongin.yang@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '11',
                'subNum' => '8884567',
                'department' => 'Networks & Security',
                'officeBuilding' => 'N28',
                'officeFloor' => '4',
                'officeRoom' => '415',
                'qualification' => 'PhD in Cyber Security',
                'facCode' => 'FC',
            ],
        ]);

        DB::table('lecturer')->insertOrIgnore([
            [
                'staffNum' => 'L2001',
                'fName' => 'Lily',
                'lName' => 'Morrow',
                'ic' => '021017016001',
                'email' => 'lily.morrow@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '12',
                'subNum' => '9991234',
                'department' => 'Chemistry',
                'officeBuilding' => 'C17',
                'officeFloor' => '2',
                'officeRoom' => '201',
                'qualification' => 'PhD in Organic Chemistry',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2002',
                'fName' => 'Haewon',
                'lName' => 'Oh',
                'ic' => '030225016002',
                'email' => 'haewon.oh@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '13',
                'subNum' => '8881234',
                'department' => 'Mathematical Sciences',
                'officeBuilding' => 'C22',
                'officeFloor' => '3',
                'officeRoom' => '305',
                'qualification' => 'PhD in Applied Mathematics',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2003',
                'fName' => 'Yoonah',
                'lName' => 'Seol',
                'ic' => '040126016003',
                'email' => 'yoonah.seol@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '19',
                'subNum' => '7771234',
                'department' => 'Biosciences',
                'officeBuilding' => 'T02',
                'officeFloor' => '4',
                'officeRoom' => '402',
                'qualification' => 'PhD in Biotechnology',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2004',
                'fName' => 'Jinsol',
                'lName' => 'Bae',
                'ic' => '041228016004',
                'email' => 'jinsol.bae@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '17',
                'subNum' => '6661234',
                'department' => 'Physics',
                'officeBuilding' => 'C18',
                'officeFloor' => '2',
                'officeRoom' => '210',
                'qualification' => 'PhD in Solid State Physics',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2005',
                'fName' => 'Jiwoo',
                'lName' => 'Kim',
                'ic' => '050413016005',
                'email' => 'jiwoo.kim@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '14',
                'subNum' => '5551234',
                'department' => 'Chemistry',
                'officeBuilding' => 'C19',
                'officeFloor' => '3',
                'officeRoom' => '315',
                'qualification' => 'PhD in Analytical Chemistry',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2006',
                'fName' => 'Kyujin',
                'lName' => 'Jang',
                'ic' => '060526016006',
                'email' => 'kyujin.jang@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '16',
                'subNum' => '4441234',
                'department' => 'Mathematical Sciences',
                'officeBuilding' => 'C22',
                'officeFloor' => '4',
                'officeRoom' => '420',
                'qualification' => 'Master of Statistics',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2007',
                'fName' => 'Heeseung',
                'lName' => 'Lee',
                'ic' => '011015016007',
                'email' => 'heeseung.lee@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '18',
                'subNum' => '3331234',
                'department' => 'Biosciences',
                'officeBuilding' => 'T02',
                'officeFloor' => '3',
                'officeRoom' => '308',
                'qualification' => 'PhD in Microbiology',
                'facCode' => 'FS',
            ],
            [
                'staffNum' => 'L2008',
                'fName' => 'Jongseong',
                'lName' => 'Park',
                'ic' => '020420016008',
                'email' => 'jongseong.park@staff.utm.my',
                'pass' => $password,
                'countryCode' => '60',
                'phoneOp' => '11',
                'subNum' => '2221234',
                'department' => 'Physics',
                'officeBuilding' => 'C18',
                'officeFloor' => '2',
                'officeRoom' => '222',
                'qualification' => 'PhD in Optics',
                'facCode' => 'FS',
            ],
        ]);
    }
}